### PR TITLE
Windows testing by appveyor

### PR DESCRIPTION
**Pull request by TeroFrondelius**

### CODE REVIEW

**Comment by TeroFrondelius** [comment]
Strange travis passes but AppVeyor fails.

**Comment by TeroFrondelius** [comment]
@ahojukka5 comments?

**Comment by ahojukka5** [comment]
We should tag FEMQuad after changes. I think now it's good to go?

**Comment by ahojukka5** [comment]
It looks that Appveoyr is using a 32-bit version of Julia and this is causing tests to fail. But actually, it would be a good idea to have JuliaFEM working on 32-bit machines if someone is interested in doing light-weight FEM using IoT devices and so on.

**Pull request merged**
